version: '3'
services:
  db:
    image: mysql
    build: 
      context: ./mysql
    volumes:
      - mysqldata:/var/lib/mysql
    container_name: db
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: enigma
    ports:
      - 3306:3306
  pma:
    image: phpmyadmin/phpmyadmin
    build: 
      context: ./phpmyadmin
    container_name: pma
    depends_on:
      - db
    environment:
      - PMA_ARBITARY=1
    restart: always
    ports:
      - 8080:80
  nginx:
    image: nginx
    build: 
      context: ./mysql
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes: 
      - ./src:/var/www:ro
volumes:
  mysqldata:
    driver: local