version: '3'
services:
  db:
    image: postgres
    restart: always
    container_name: db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DATABASE: enigma
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
  nginx:
    image: nginx
    build: 
      context: ./nginx
    container_name: nginx
    restart: on-failure
    ports:
      - 80:80
      - 443:443
    volumes: 
      - ./app:/var/www/:ro
  golang:
    container_name: golang
    restart: always
    ports:
      - 8002:8002
    build:
      context: ./app/server
    depends_on:
      - db
      - nginx
volumes:
  mysqldata:
    driver: local