version: '3'
services:
  db:
    image: mysql:8.0
    volumes:
      - mysqldata:/var/lib/mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --default-authentication-plugin=mysql_native_password
    container_name: db
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
  pma:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    depends_on:
      - db
    environment:
      - PMA_ARBITARY=1
    restart: always
    ports:
      - 8080:80
    volumes:
      - /sessions
  nginx:
    image: nginx
    build: 
      context: ./nginx
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes: 
      - ./app:/var/www/:ro
  golang:
    build:
      context: ./app/server
    depends_on: 
      - nginx
      - db
volumes:
  mysqldata:
    driver: local