database:
  default: mysql
  mysql:
    host: db
    port: 3306
    user: root
    dbname: enigma_go
    password: root
    protocol: tcp
  postgres:
    host: db
    port: 5432
    user: root
    password: root
    dbname: enigma
router:
  port: 8002